# learn dense 3d image embedding with V-net
SYSTEM:
  NUM_GPUS: 1
  NUM_CPUS: 2
MODEL:
  INPUT_SIZE: [ 17, 129, 129 ]
  OUTPUT_SIZE: [ 17, 129, 129 ]
  ARCHITECTURE: unet_3d
  BLOCK_TYPE: residual_se
  FILTERS: [32, 64, 96, 128, 160]
  OUT_PLANES: 16
  TARGET_OPT: ["e"]
  LOSS_OPTION: [[ "DiscriminativeLoss" ]]
  LOSS_WEIGHT: [ [ 1.0 ] ]
  WEIGHT_OPT: [ [ "0" ] ]
  OUTPUT_ACT: [[ "none" ]]
  ISOTROPY: [ False, True, True, True, True]
  NORM_MODE: bn
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  NAME: AdamW
  ITERATION_RESTART: True
  BASE_LR: 1e-04
  STEPS: (30000, 60000)
  ITERATION_SAVE: 200
  ITERATION_TOTAL: 55000
  ITERATION_VAL: 200
DATASET:
  IMAGE_NAME: images/SNEMI3D-train-mip1-raw.h5
  LABEL_NAME: golds/SNEMI3D-train-mip1-gold.h5
  VAL_IMAGE_NAME: images/SNEMI3D-test-mip1-raw.h5
  VAL_LABEL_NAME: golds/SNEMI3D-test-mip1-gold.h5
  INPUT_PATH: /braindat/lab/liusl/flywire/biologicalgraphs/biologicalgraphs/neuronseg/
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-Unet-metric-snemi3d
INFERENCE:
  OUTPUT_PATH: /data12T/janechen/SNEMI_UNet/test
  OUTPUT_NAME: result.h5
  OUTPUT_ACT: [ "none"]
AUGMENTOR:
  SMOOTH: False
  MISSINGPARTS:
    ENABLED: False
    P: 0.3
  MISSINGSECTION:
    ENABLED: False
    P: 0.3
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  ROTATE:
    ENABLED: False
  RESCALE:
    ENABLED: False
  FLIP:
    ENABLED: True
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: True
  MISALIGNMENT:
    DISPLACEMENT: 32
    P: 0.3
    ENABLED: False
    ROTATE_RATIO: 0.0
  MOTIONBLUR:
    ENABLED: False
