SYSTEM:
  NUM_GPUS: 1
  NUM_CPUS: 2
MODEL:
  INPUT_SIZE: [ 16, 128, 128 ]
  ARCHITECTURE: EdgeNetwork
  POOLING_LAYER: True  # used in unet
  IN_PLANES: 5
  FILTERS: [16, 32, 64, 128]
  LOSS_OPTION:
    [[ "classification_MSE" ]]
  LOSS_WEIGHT: [[ 1.0 ]]
  WEIGHT_OPT: [[ "0" ]]
  OUTPUT_ACT: [[ "none"]]
  TARGET_OPT: ["0"]
  MIXED_PRECESION: True
  MASK_EMBED: True
  EMBED_REDUCTION: [16, 3]
  IMAGE_MODEL_CFG: configs/test-neuron-swin-connector.yaml
  IMAGE_MODEL_CKPT: /braindat/lab/liusl/flywire/experiment/image-swin-isoem-wu-1cl/checkpoint_best.pth
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  # DECAY_LOSS_WEIGHT: True
  NAME: AdamW
  BASE_LR: 5e-03
  STEPS: (250000, 350000)
  ITERATION_SAVE: 200
  ITERATION_TOTAL: 200000
  ITERATION_VAL: 200
  SAMPLES_PER_BATCH: 32 # PER GPU
DATASET:
  RELABEL: False
  DATA_CHUNK_ITER: 40
  CONNECTOR_DATSET: True
  MORPHOLOGY_DATSET: True
  IMAGE_NAME:
  LABEL_NAME:
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/morph-EmbedEdgeNetwork-connector
  DO_MULTI_VOLUME: True
  DISTRIBUTED: True
INFERENCE:
  OUTPUT_ACT: ["none"]
  SAMPLES_PER_BATCH: 64 # per gpu
AUGMENTOR:
  SMOOTH: False
  MISSINGPARTS:
    ENABLED: False
    P: 0.1
  MISSINGSECTION:
    ENABLED: False
    P: 0.3
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  ROTATE:
    ENABLED: True
  RESCALE:
    ENABLED: True
  FLIP:
    ENABLED: True
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: True
  MISALIGNMENT:
    P: 0.3
    ENABLED: False
  MOTIONBLUR:
    ENABLED: False