# learn dense 3d image embedding with V-net
MODEL:
  INPUT_SIZE: [ 31, 161, 161 ]
  OUTPUT_SIZE: [ 31, 161, 161 ]
  ARCHITECTURE: unet_3d
  BLOCK_TYPE: residual_se
  FILTERS: [32, 64, 96, 128, 160]
  OUT_PLANES: 16
  TARGET_OPT: ["e"]
  LOSS_OPTION:
    [[ "DiscriminativeLoss", "ConnectionLoss" ]]
  LOSS_WEIGHT: [[ 1.0, 0.1 ]]
  WEIGHT_OPT: [[ "0", "0" ]]
  OUTPUT_ACT: [[ "none",  "none" ]]
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  NAME: Adam
  BASE_LR: 1e-03
  STEPS: (250000, 500000)
  ITERATION_SAVE: 8000
  ITERATION_TOTAL: 2000000
  ITERATION_VAL: 4000
DATASET:
  CONNECTOR_DATSET: True
  IMAGE_NAME:
  LABEL_NAME:
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-Unet-connector-test
  DO_MULTI_VOLUME: True
  DISTRIBUTED: True
INFERENCE:
  OUTPUT_ACT: ["none"]
AUGMENTOR:
  SMOOTH: False
  MISSINGPARTS:
    ENABLED: False
  MISSINGSECTION:
    ENABLED: False
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  ROTATE:
    ENABLED: True
  RESCALE:
    ENABLED: True
  FLIP:
    ENABLED: True
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: False
  MISALIGNMENT:
    ENABLED: False
  MOTIONBLUR:
    ENABLED: False