SYSTEM:
  NUM_GPUS: 1
  NUM_CPUS: 1
MODEL:
  # LABEL_EROSION: 1
  INPUT_SIZE: [ 16, 128, 128 ]
  OUTPUT_SIZE: [ 16, 128, 128 ]
  ARCHITECTURE: swin_unetr
  ISOTROPY: [True, False, True, True, True]
  POOLING_LAYER: True  # used in unet
  OUT_PLANES: 16
  TARGET_OPT: ["e"]
  LOSS_OPTION:
    [[ "DiscriminativeLoss", "ConnectionLoss" ]]
  LOSS_WEIGHT: [[ 1.0, 0.1 ]]
  WEIGHT_OPT: [[ "0", "0" ]]
  OUTPUT_ACT: [[ "none",  "none" ]]
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  NAME: AdamW
  BASE_LR: 2e-03
  WARMUP_FACTOR: 2e-5
  WARMUP_ITERS: 50000
  STEPS: (300000, 800000)
  ITERATION_SAVE: 8000
  ITERATION_TOTAL: 2000000
  ITERATION_VAL: 20
  SAMPLES_PER_BATCH: 4 # PER GPU
DATASET:
  CONNECTOR_DATSET: True
  IMAGE_NAME:
  LABEL_NAME:
  VAL_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_vali_filtered
  INPUT_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_train
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-Unet-connector-test
  DO_MULTI_VOLUME: True
  DISTRIBUTED: True
  DATA_CHUNK_ITER: 800
  RELABEL: True
INFERENCE:
  OUTPUT_ACT: ["none"]
  SAMPLES_PER_BATCH: 4 # per gpu
AUGMENTOR:
  ADDITIONAL_TARGETS_NAME: [ 'label', 'valid_mask' ]
  ADDITIONAL_TARGETS_TYPE: [ 'mask', 'mask' ]
  SMOOTH: True
  MISSINGPARTS:
    ENABLED: False
  MISSINGSECTION:
    ENABLED: False
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  ROTATE:
    ENABLED: True
  RESCALE:
    ENABLED: True
  FLIP:
    ENABLED: True
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: False
  MISALIGNMENT:
    ENABLED: False
  MOTIONBLUR:
    ENABLED: False