MODEL:
  INPUT_SIZE: [ 16, 128, 128 ]
  OUTPUT_SIZE: [ 16, 128, 128 ]
  ARCHITECTURE: swin_unetr
 # LABEL_EROSION: 1
  ISOTROPY: [True, False, True, True, True]
  POOLING_LAYER: True  # used in unet
  OUT_PLANES: 24  # embedding dim should also be changed in model.utils.misc and visualizer
  TARGET_OPT: ["e"]
  LOSS_OPTION:
    [[ "DiscriminativeLoss", "ConnectionLoss" ]]
  LOSS_WEIGHT: [[ 1.0, 1.0 ]]
  WEIGHT_OPT: [[ "0", "0" ]]
  OUTPUT_ACT: [[ "none",  "none" ]]
  MIXED_PRECESION: True
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  NAME: AdamW
  BASE_LR: 2e-03
  WARMUP_FACTOR: 2e-5
  WARMUP_ITERS: 50000
  STEPS: (250000, 350000)
  ITERATION_SAVE: 8000
  ITERATION_TOTAL: 2000000
  ITERATION_VAL: 4000
  SAMPLES_PER_BATCH: 4 # PER GPU
DATASET:
  CONNECTOR_DATSET: True
  IMAGE_NAME:
  LABEL_NAME:
  VAL_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_vali_filtered
  INPUT_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_train
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-Unet-connector-test
  DO_MULTI_VOLUME: True
  DISTRIBUTED: True
INFERENCE:
  OUTPUT_PATH: /data12T/janechen/SNEMI_UNet/test
  OUTPUT_NAME: result.h5
  OUTPUT_ACT: ["none"]
  SAMPLES_PER_BATCH: 4 # per gpu
AUGMENTOR:
  SMOOTH: False
  MISSINGPARTS:
    ENABLED: True
    P: 0.1
  MISSINGSECTION:
    ENABLED: True
    P: 0.3
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  ROTATE:
    ENABLED: True
  RESCALE:
    ENABLED: True
  FLIP:
    ENABLED: True
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: True
  MISALIGNMENT:
    P: 0.3
    ENABLED: True
  MOTIONBLUR:
    ENABLED: False