# learn dense 3d image embedding with V-net
MODEL:
  INPUT_SIZE: [ 32, 160, 160 ]
  OUTPUT_SIZE: [ 32, 160, 160 ]
  ARCHITECTURE: unet_3d
  BLOCK_TYPE: residual_se
  FILTERS: [32, 64, 96, 128, 160]
  OUT_PLANES: 16
  TARGET_OPT: ["e"]
  LOSS_OPTION:
    [[ "DiscriminativeLoss", "ConnectionLoss" ]]
  LOSS_WEIGHT: [[ 1.0, 1.0 ]]
  WEIGHT_OPT: [[ "0", "0" ]]
  OUTPUT_ACT: [[ "none",  "none" ]]
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
  ITERATION_VAL: 400
DATASET:
  CONNECTOR_DATSET: True
  IMAGE_NAME:
  LABEL_NAME:
  VAL_PATH: /braindat/lab/liusl/flywire/block_data/val_30_sub
  INPUT_PATH: /braindat/lab/liusl/flywire/block_data/train_30
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-Unet-connector
  DO_MULTI_VOLUME: True
  DISTRIBUTED: True
  DATA_CHUNK_ITER: 400
INFERENCE:
  OUTPUT_PATH: /data12T/janechen/SNEMI_UNet/test
  OUTPUT_NAME: result.h5
  OUTPUT_ACT: ["none"]
AUGMENTOR:
  SMOOTH: False
  MISSINGPARTS:
    ENABLED: False
  MISSINGSECTION:
    ENABLED: False
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  ROTATE:
    ENABLED: True
  RESCALE:
    ENABLED: True
  FLIP:
    ENABLED: True
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: False
  MISALIGNMENT:
    ENABLED: False
  MOTIONBLUR:
    ENABLED: False