MODEL:
  INPUT_SIZE: [ 16, 128, 128 ]
  OUTPUT_SIZE: [ 16, 128, 128 ]
  ARCHITECTURE: swin_unetr
 # LABEL_EROSION: 1
  ISOTROPY: [True, False, True, True, True]
  POOLING_LAYER: True  # used in unet
  OUT_PLANES: 16  # embedding dim should also be changed in model.utils.misc and visualizer
  TARGET_OPT: ["e"]
  LOSS_OPTION:
    [[ "DiscriminativeLoss", "ConnectionLoss" ]]
  LOSS_WEIGHT: [[ 0.2, 1.0 ]]
  WEIGHT_OPT: [[ "0", "0" ]]
  OUTPUT_ACT: [[ "none",  "none" ]]
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  # DECAY_LOSS_WEIGHT: True
  ITERATION_RESTART: True
  NAME: AdamW
  BASE_LR: 5e-04
  WARMUP_FACTOR: 2e-5
  WARMUP_ITERS: 50000
  STEPS: (250000, 450000)
  ITERATION_SAVE: 8000
  ITERATION_TOTAL: 500000
  ITERATION_VAL: 4000
  SAMPLES_PER_BATCH: 4 # PER GPU
DATASET:
  CONNECTOR_DATSET: True
  IMAGE_NAME:
  LABEL_NAME:
  VAL_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_hard_vali
  INPUT_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_train_1000_hard
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-swin-finetune-hard
  DO_MULTI_VOLUME: True
  DISTRIBUTED: True
  RELABEL: False
INFERENCE:
  OUTPUT_ACT: ["none"]
  SAMPLES_PER_BATCH: 4 # per gpu
AUGMENTOR:
  SMOOTH: False
  MISSINGPARTS:
    ENABLED: False
    P: 0.3
  MISSINGSECTION:
    ENABLED: False
    P: 0.3
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  ROTATE:
    ENABLED: True
  RESCALE:
    ENABLED: True
  FLIP:
    ENABLED: True
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: True
  MISALIGNMENT:
    DISPLACEMENT: 32
    P: 0.3
    ENABLED: False
    ROTATE_RATIO: 0.0
  MOTIONBLUR:
    ENABLED: False