# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/defaults.py
SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 2
MODEL:
  INPUT_SIZE: [17, 227, 227]
  OUTPUT_SIZE: [17, 227, 227]
  IN_PLANES: 1
  ISOTROPY: [ False, True, True, True, True ]
  OUT_PLANES: 16
  TARGET_OPT: ["e"]
  LOSS_OPTION:
    [[ "DiscriminativeLoss", "ConnectionLoss" ]]
  LOSS_WEIGHT: [[ 1.0, 0.1 ]]
  WEIGHT_OPT: [[ "0", "0" ]]
  OUTPUT_ACT: [[ "none",  "none" ]]
  NORM_MODE: bn
DATASET:
  CONNECTOR_DATSET: True
  IMAGE_NAME:
  LABEL_NAME:
  VAL_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_vali_filtered
  INPUT_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_train
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-Unet-connector-test
  DO_MULTI_VOLUME: True
  DISTRIBUTED: True
  DATA_CHUNK_ITER: 800
  RELABEL: False
  PAD_SIZE: [4, 64, 64]
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  NAME: Adam
  BASE_LR: 1e-04
  STEPS: (100000, 150000)
  ITERATION_SAVE: 8000
  ITERATION_TOTAL: 500000
  ITERATION_VAL: 4000
  SAMPLES_PER_BATCH: 2 # PER GPU
MONITOR:
  ITERATION_NUM: [20, 200]
INFERENCE:
  INPUT_SIZE: [17, 257, 257]
  OUTPUT_SIZE: [17, 257, 257]
  OUTPUT_ACT: ["sigmoid"]
  IMAGE_NAME: test_input.tif # or path to your test images
  OUTPUT_PATH: /data12T/janechen/SNEMI3D/test
  OUTPUT_NAME: result.tif
  PAD_SIZE: [0, 0, 0]
  UNPAD: False
  AUG_MODE: min
  AUG_NUM: 4
  STRIDE: [18, 32, 32]
  SAMPLES_PER_BATCH: 8 # per gpu
