# learn dense 3d image embedding with V-net
MODEL:
  INPUT_SIZE: [ 17, 129, 129 ]
  OUTPUT_SIZE: [ 17, 129, 129 ]
  ARCHITECTURE: unet_3d
  BLOCK_TYPE: residual_se
  FILTERS: [32, 64, 96, 128, 160]
  OUT_PLANES: 16
  TARGET_OPT: ["e"]
  LOSS_OPTION:
    [[ "DiscriminativeLoss", "ConnectionLoss" ]]
  LOSS_WEIGHT: [[ 0.2, 1.0 ]]
  WEIGHT_OPT: [[ "0", "0" ]]
  OUTPUT_ACT: [[ "none",  "none" ]]
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
  LR_SCHEDULER_NAME: "MultiStepLR"
  ITERATION_RESTART: True
  NAME: AdamW
  BASE_LR: 5e-04
  WARMUP_FACTOR: 2e-5
  WARMUP_ITERS: 50000
  STEPS: (100000, 250000)
  ITERATION_SAVE: 2000
  ITERATION_TOTAL: 500000
  ITERATION_VAL: 2000
  SAMPLES_PER_BATCH: 4 # PER GPU
DATASET:
  CONNECTOR_DATSET: True
  IMAGE_NAME:
  LABEL_NAME:
  VAL_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_hard_vali
  INPUT_PATH: /braindat/lab/liusl/flywire/block_data/v2/30_percent_train_1000_hard
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-unet-finetune-hard
  DO_MULTI_VOLUME: True
  DISTRIBUTED: True
  RELABEL: False
INFERENCE:
  OUTPUT_ACT: ["none"]
  SAMPLES_PER_BATCH: 4 # per gpu
AUGMENTOR:
  SMOOTH: False
  MISSINGPARTS:
    ENABLED: False
  MISSINGSECTION:
    ENABLED: False
  CUTNOISE:
    ENABLED: False
  CUTBLUR:
    ENABLED: False
  ROTATE:
    ENABLED: True
  RESCALE:
    ENABLED: True
  FLIP:
    ENABLED: True
  ELASTIC:
    ENABLED: False
  GRAYSCALE:
    ENABLED: False
  MISALIGNMENT:
    ENABLED: False
  MOTIONBLUR:
    ENABLED: False