# learn dense 3d image embedding with anisotropy swinUnetr
SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 2
MODEL:
  INPUT_SIZE: [ 32, 160,160 ]
  OUTPUT_SIZE: [ 32, 160, 160 ]
#  INPUT_SIZE: [ 28, 128,128 ]
#  OUTPUT_SIZE: [ 28, 128, 128 ]
  ARCHITECTURE: swin_unetr
  ISOTROPY: [True, False, False, False, True]
  POOLING_LAYER: True  # used in unet
  OUT_PLANES: 16
  TARGET_OPT: ["e"]
  LOSS_OPTION: [[ "DiscriminativeLoss" ]]
  LOSS_WEIGHT: [ [ 1.0 ] ]
  WEIGHT_OPT: [ [ "0" ] ]
  OUTPUT_ACT: [[ "none" ]]
MONITOR:
  ITERATION_NUM: [20, 200]
SOLVER:
#  LR_SCHEDULER_NAME: "MultiStepLR"
  BASE_LR: 2e-3
  SAMPLES_PER_BATCH: 2
  NAME: "AdamW"
  MOMENTUM: 0.9
  ITERATION_SAVE: 5000 # check memory
  STEPS: (450000, 500000)
  WARMUP_FACTOR: 2e-4
  WARMUP_ITERS: 5000
  ITERATION_TOTAL: 250000
  # ITERATION_RESTART: True
DATASET:
  IMAGE_NAME: im_Atrain.h5@im_Btrain.h5@im_Ctrain.h5
  LABEL_NAME: neuron_A_train.h5@neuron_B_train.h5@neuron_C_train.h5
  VAL_IMAGE_NAME: im_Aval.h5@im_Bval.h5@im_Cval.h5
  VAL_LABEL_NAME: neuron_A_val.h5@neuron_B_val.h5@neuron_C_val.h5
  INPUT_PATH: /braindat/lab/liusl/cremi/train_93-32_vali
  OUTPUT_PATH: /braindat/lab/liusl/flywire/experiment/image-swin-metric-only
INFERENCE:
  OUTPUT_PATH: /data12T/janechen/SNEMI_UNet/test
  OUTPUT_NAME: result.h5
  OUTPUT_ACT: [ "none"]
